server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/truerally
    username: ${DB_USER:truerally_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # creates/updates schema in dev (switch off in prod)
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-ms: 300000      # 5 minutes
  refresh-token-validity-ms: 86400000   # 1 day
  issuer: truerally-auth
  ##secret: dev-please-change-me-32chars-minimum-123456

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  pattern:
    level: "%5p [cid:%X{correlationId}] [latency:%X{latencyMs}ms]"