# compose.yml
name: truerally
services:
  postgres:
    image: postgres:16-alpine
    container_name: truerally-postgres
    environment:
      POSTGRES_DB: truerally
      POSTGRES_USER: truerally_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:3.6
    container_name: truerally-kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: truerally-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  minio:
    image: minio/minio:RELEASE.2024-03-21T23-13-43Z
    container_name: truerally-minio
    environment:
      MINIO_ROOT_USER: truerally
      MINIO_ROOT_PASSWORD: truerally-secret
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: truerally-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./local-dev/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  postgres_data:
  minio_data: